# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ff2d54516a49d1bfb32408cd4cb2a4f1b0a4d044ac679c571f2a9a046cffb43c584d6ca318d19fd574ead3c2118bf69690976b2b94a3af0b19a3ab132635f22

test:
  secret_key_base: 3e61df2776b5db0b7b1f83338a90ad2ae8bcc937b53c5696b8581161065568ca529b54ee875dcb2fa568a991870a4a3c5f89a8661ca57c62145a0bc119d7b790

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
